name: GitHub Actions
run-name: Testing code ğŸš€
on: [push]
jobs:
  Python-format:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: python3 --version
      - run: python3 -m venv venv
      - name: Format python files
        run: |
          . venv/bin/activate
          pip install -r requirements_dev.txt
          make black-check
          deactivate
      - run: echo "ğŸ This job's status is ${{ job.status }}."

  Python-lint:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: python3 --version
      - run: python3 -m venv venv
      - name: Lint python files
        run: |
          . venv/bin/activate
          pip install -r requirements_dev.txt
          make pyflakes
          deactivate
      - run: echo "ğŸ This job's status is ${{ job.status }}."

  Google-Colaboratory-notebook-diff:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: python3 --version
      - run: python3 -m venv venv
      - name: Diff notebook
        run: |
          . venv/bin/activate
          pip install -r requirements_dev.txt
          make notebook-check
          deactivate
      - run: echo "ğŸ This job's status is ${{ job.status }}."
